services:
  postgres:
    image: postgres:18
    container_name: my_postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: budgetbuddy
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - database_network

networks:
  database_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
